adding all the icons + updating to laravel 11
Faisal50x/blade-ionicons pull request #8
Opened 2024-05-29 18:11 UTC by swapnilsarwe

* updating to support laravel 11
* adding all the updated icons

2024-05-29 18:14 UTC, swapnilsarwe commented
@Foysal50x 
have a look at the PR - whenever you get time.
Possibly mark it as a major release

2024-05-30 13:40 UTC, Foysal50x requested changes

2024-05-30 13:40 UTC, Foysal50x commented on composer.json
> +        "codeat3/blade-icon-generation-helpers": "^0.8.0",
add this package as a dev dependancy 
```json
        "codeat3/blade-icon-generation-helpers": "^0.8.0",
```

2024-05-30 13:58 UTC, swapnilsarwe commented on composer.json
> +        "codeat3/blade-icon-generation-helpers": "^0.8.0",
Sure.

2024-05-30 14:11 UTC, Foysal50x approved these changes

2024-05-30 14:15 UTC, merged